### ISSUE TITLE
Flutter project. 1 week try

### ISSUE THREAD

**Issue by min23asdw** [AreYouWorking/Air-pollution-awareness#1]

**Comment by min23asdw** [comment]
ลองเขียน app ใน android ให้สามารถ import ภาพจาก gallery ได้ก่อน  ดูว่าชอบ flutter ไหม  อาจจะลองทำไปถึงขั้น  import->add text on pic ได้เลยก็ได้

**Comment by PutawanDE** [comment]
ลองแล้วชอบครับ
